name: Deploy to Production

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /www/wwwroot/cctvwongkito.my.id

            # Menentukan php binary versi 8.5 untuk aaPanel
            PHP_BIN="/www/server/php/85/bin/php"

            # Mengatasi kendala safe.directory pada git
            git config --global --add safe.directory /www/wwwroot/cctvwongkito.my.id

            echo ">>> Change owner to deploy user"
            sudo chown -R masum-xyz:masum-xyz /www/wwwroot/cctvwongkito.my.id

            echo ">>> Pull latest code"
            git pull origin prod

            echo ">>> Change owner to web server"
            sudo chown -R www:www /www/wwwroot/cctvwongkito.my.id
            sudo chmod -R 775 /www/wwwroot/cctvwongkito.my.id/storage /www/wwwroot/cctvwongkito.my.id/bootstrap/cache

            echo ">>> Enable maintenance mode"
            sudo -u www $PHP_BIN artisan down || true

            echo ">>> Composer install"
            sudo -u www $PHP_BIN /usr/bin/composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

            echo ">>> Migrate database"
            sudo -u www $PHP_BIN artisan migrate --force

            echo ">>> Clear & optimize Laravel"
            sudo -u www $PHP_BIN artisan optimize:clear
            sudo -u www $PHP_BIN artisan optimize

            echo ">>> Disable maintenance mode"
            sudo -u www $PHP_BIN artisan up

      - name: Send Telegram Notification
        run: |
          MSG="🚀 Deployment Berhasil

          Project: CRM CCTV Wongkito
          Site : https://cctvwongkito.my.id
          Branch: prod
          Author: $(git log -1 --pretty=%an)
          Commit: $(git log -1 --pretty=%B)

          Tanggal: $(date +"%d %b %Y %H:%M:%S")"

          curl -s -X POST "https://api.telegram.org/bot7606903409:AAHG_hyBsE1lfZOMZv5sqizwUZkBCE8Sk-A/sendMessage" \
          -d chat_id=1255532464 \
          -d text="$MSG" \
          -d parse_mode=Markdown
